include "application"

sim {
  algorithm = "both"
  runDurationMs = 15000

  graph {
    topology = "random"
    numNodes = 15
    edgeProbability = 0.4
    seed = 300
  }

  traffic {
    tickIntervalMs = 150
    defaultPdf = [
      { msg = "PING", p = 0.40 },
      { msg = "GOSSIP", p = 0.20 },
      { msg = "WORK", p = 0.40 }
    ]
    perNodePdf = [
      { node = 5, pdf = [ { msg = "WORK", p = 0.80 }, { msg = "PING", p = 0.20 } ] }
    ]
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 100 },
      { node = 3, tickEveryMs = 200 }
    ]
    inputs = [
      { node = 1 },
      { node = 2 },
      { node = 4 }
    ]
  }
}
