include "application"

sim {
  algorithm = "both"
  runDurationMs = 15000
  graph {
    topology = "random"
    numNodes = 20
    edgeProbability = 0.4
    seed = 999
  }
  traffic {
    tickIntervalMs = 100
    defaultPdf = [
      { msg = "PING", p = 0.40 },
      { msg = "GOSSIP", p = 0.20 },
      { msg = "WORK", p = 0.40 }
    ]
    perNodePdf = [
      { node = 5, pdf = [{ msg = "WORK", p = 0.80 }, { msg = "PING", p = 0.20 }] }
    ]
  }
  initiators {
    timers = [
      { node = 0, tickEveryMs = 50 },
      { node = 3, tickEveryMs = 100 }
    ]
    inputs = [
      { node = 1 },
      { node = 7 }
    ]
  }
}
