include "application"

sim {
  algorithm = "bully"
  runDurationMs = 8000

  graph {
    topology = "complete"
    numNodes = 8
    edgeProbability = 1.0
    seed = 100
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 300 }
    ]
    inputs = [
      { node = 1 }
    ]
  }
}
