include "application"

netgamesim {
  topology = "ring"
  numNodes = 10
  edgeProbability = 0.0
  seed = 20260413
}

sim {
  algorithm = "itai-rodeh"
  runDurationMs = 10000

  messages {
    types = ["CONTROL", "PING", "WORK"]
  }

  edgeLabeling {
    default = ["CONTROL", "PING", "WORK"]
    overrides = []
  }

  traffic {
    defaultPdf = [
      { msg = "PING", p = 1.0 }
    ]
    perNodePdf = []
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 200, mode = "pdf" }
    ]
    inputs = [
      { node = 1 }
    ]
  }
}
