include "application"

sim {
  algorithm = "itai-rodeh"
  runDurationMs = 12000

  graph {
    topology = "ring"
    numNodes = 10
    edgeProbability = 0.0
    seed = 200
  }

  edgeLabeling {
    default = ["CONTROL", "PING", "WORK"]
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 100 }
    ]
    inputs = []
  }
}
