include "application"

netgamesim {
  topology = "tree"
  numNodes = 15
  edgeProbability = 0.0
  seed = 42
}

sim {
  algorithm = "tree-leader"
  runDurationMs = 12000

  graph {
    topology = "tree"
    numNodes = 15
    edgeProbability = 0.0
    seed = 42
  }

  edgeLabeling {
    default = ["CONTROL", "PING", "WORK"]
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 200 }
    ]
    inputs = []
  }
}
