include "application"

netgamesim {
  topology = "tree"
  numNodes = 7
  edgeProbability = 0.0
  seed = 20260417
}

sim {
  algorithm = "tree-leader"
  runDurationMs = 8000

  graph {
    topology = "tree"
    numNodes = 7
    edgeProbability = 0.0
    seed = 20260417
  }

  edgeLabeling {
    default = ["CONTROL", "PING", "WORK"]
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 300 }
    ]
    inputs = []
  }
}
